// Generated by bundle_submission.py. Do not edit manually.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <memory>
#include <vector>
#include <chrono>
#include <functional>
#include <optional>
#include <utility>
#include <cstdint>
#include <string>
#include <cstddef>
#include <algorithm>
#include <stdexcept>
#include <sstream>

// begin C:/Users/cttg8/Desktop/NYPC 2026/src/negamax_agent.h


// begin C:/Users/cttg8/Desktop/NYPC 2026/src/agent.h


// begin C:/Users/cttg8/Desktop/NYPC 2026/src/state.h


struct Move {
    int r1, c1, r2, c2;

    bool is_pass() const;
    bool operator==(const Move& other) const;
};

inline constexpr Move PASS_MOVE = {-1, -1, -1, -1};

class State {
public:
    State(int rows, int cols, const std::vector<std::vector<int>>& init_grid);
    State(const State&) = default;

    State clone() const;

    void apply(Move m);
    void undo();
    int undo_depth() const;

    std::vector<Move> legal_moves() const;
    bool is_legal(const Move& m) const;
    bool is_terminal() const;
    std::pair<int, int> scores() const;
    int winner() const;
    double reward(int player) const;

    int current_player() const;
    int rows() const;
    int cols() const;
    int8_t cell_value(int r, int c) const;
    int8_t cell_owner(int r, int c) const;

    bool operator==(const State& other) const;
    uint64_t hash() const;

    std::string to_string() const;

private:
    struct UndoRecord {
        Move move;
        int prev_consecutive_passes;
        int prev_player;
        uint64_t prev_hash;

        struct CellDelta {
            int idx;
            int8_t old_val;
            int8_t old_owner;
        };

        std::vector<CellDelta> deltas;
    };

    int rows_;
    int cols_;
    std::vector<int8_t> grid_;
    std::vector<int8_t> owners_;
    int current_player_;
    int consecutive_passes_;
    uint64_t zobrist_key_;

    std::vector<UndoRecord> undo_stack_;

    static uint64_t zobrist_cell_value(int pos, uint8_t value);
    static uint64_t zobrist_cell_owner(int pos, int8_t owner);
    static uint64_t zobrist_player(int player);
    static uint64_t zobrist_passes(int passes);
    static uint64_t zobrist_dimensions(int rows, int cols);

    bool border_ok(int r1, int c1, int r2, int c2) const;
    int idx(int r, int c) const;
    uint64_t compute_zobrist_key() const;
};
// end C:/Users/cttg8/Desktop/NYPC 2026/src/state.h


class Agent {
public:
    virtual ~Agent() = default;
    virtual void set_side(bool plays_first) = 0;
    virtual void initialize(const std::vector<std::vector<int>>& board) = 0;
    virtual Move choose_move(int my_time_ms, int opp_time_ms) = 0;
    virtual void apply_opponent_move(Move move) = 0;
};
// end C:/Users/cttg8/Desktop/NYPC 2026/src/agent.h

// begin C:/Users/cttg8/Desktop/NYPC 2026/src/tt.h



constexpr size_t TT_CAPACITY = 1 << 20;

enum class BoundType {
    Exact,
    Lower,
    Upper,
};

struct TranspositionEntry {
    uint64_t key;
    int depth;
    int value;
    Move best_move;
    BoundType bound;
    bool occupied;
};

class TranspositionTable {
public:
    explicit TranspositionTable(size_t capacity = TT_CAPACITY);
    const TranspositionEntry* probe(uint64_t key) const;
    void store(uint64_t key, int depth, int value, Move best_move,
               BoundType bound);
    size_t size() const;
    size_t capacity() const;
    void clear();

private:
    std::vector<TranspositionEntry> entries_;
    size_t used_;

    size_t index(uint64_t key) const;
};
// end C:/Users/cttg8/Desktop/NYPC 2026/src/tt.h


#define R 10
#define C 17

constexpr int INF = 1000000;

struct SearchConfig {
    int rows = R;
    int cols = C;
    int max_depth = 64;
    size_t tt_capacity = TT_CAPACITY;
};

struct TimeBudgetParams {
    int expected_game_plies = 38;
    int min_remaining_plies = 6;
    int clock_reserve_ms = 150;
    int min_move_budget_ms = 40;
    int max_move_budget_ms = 700;
    int time_buffer_ms = 20;
    int heavy_branch_threshold = 60;
    int medium_branch_threshold = 30;
    int light_branch_threshold = 8;
};

using EvaluateStateFn = std::function<int(const State&, int)>;
using MovePriorityFn = std::function<float(
    const State&, const Move&, std::optional<Move>, int, int, bool)>;
using ComputeTimeBudgetFn =
    std::function<int(int, int, int, const TimeBudgetParams&)>;

int evaluate_state(const State& state, int player);
float move_priority(const State& state, const Move& move,
                    std::optional<Move> tt_best_move, int depth, int ply,
                    bool is_root);
int compute_time_budget_ms(int my_time_ms, int current_ply,
                           int legal_move_count,
                           const TimeBudgetParams& params);

class NegamaxAgent : public Agent {
public:
    explicit NegamaxAgent(
        SearchConfig config = {},
        TimeBudgetParams time_budget_params = {},
        EvaluateStateFn evaluate_state_fn = evaluate_state,
        MovePriorityFn move_priority_fn = move_priority,
        ComputeTimeBudgetFn compute_time_budget_ms_fn =
            compute_time_budget_ms);

    void set_side(bool plays_first) override;
    void initialize(const std::vector<std::vector<int>>& board) override;
    Move choose_move(int my_time_ms, int opp_time_ms) override;
    void apply_opponent_move(Move move) override;

private:
    void ensure_initialized() const;
    void order_moves(const State& state, std::vector<Move>& moves,
                     std::optional<Move> tt_best_move, int depth, int ply,
                     bool is_root) const;
    std::pair<int, Move> negamax(
        State& state, int depth, int alpha, int beta, int player,
        std::chrono::steady_clock::time_point deadline, bool& timed_out,
        int ply = 0, bool is_root = false);
    std::pair<int, Move> iterative_deepening(State& state, int max_depth,
                                             int time_budget_ms);

    SearchConfig config_;
    TimeBudgetParams time_budget_params_;
    EvaluateStateFn evaluate_state_;
    MovePriorityFn move_priority_;
    ComputeTimeBudgetFn compute_time_budget_ms_;
    int my_side_;
    std::optional<State> state_;
    TranspositionTable tt_;
};
// end C:/Users/cttg8/Desktop/NYPC 2026/src/negamax_agent.h

// begin C:/Users/cttg8/Desktop/NYPC 2026/src/negamax_agent.cpp


int evaluate_state(const State& state, int player)
{
    auto scores = state.scores();
    int value = scores.first - scores.second;
    if (player == 1) {
        value = -value;
    }
    return value;
}

float move_priority(const State& /*state*/, const Move& move,
                    std::optional<Move> /*tt_best_move*/, int /*depth*/,
                    int /*ply*/, bool /*is_root*/)
{
    const int height = move.r2 - move.r1 + 1;
    const int width = move.c2 - move.c1 + 1;
    return static_cast<float>(height * width);
}

int compute_time_budget_ms(int my_time_ms, int current_ply,
                           int legal_move_count,
                           const TimeBudgetParams& params)
{
    const int usable_time_ms =
        std::max(1, my_time_ms - params.clock_reserve_ms);
    const int remaining_plies =
        std::max(params.min_remaining_plies,
                 params.expected_game_plies - current_ply);
    int budget = usable_time_ms / remaining_plies;

    if (legal_move_count > params.heavy_branch_threshold) {
        budget = budget * 3 / 2;
    } else if (legal_move_count > params.medium_branch_threshold) {
        budget = budget * 5 / 4;
    } else if (legal_move_count < params.light_branch_threshold) {
        budget = budget * 3 / 4;
    }

    budget = std::clamp(budget, params.min_move_budget_ms,
                        params.max_move_budget_ms);
    return std::min(budget, std::max(1, my_time_ms - params.time_buffer_ms));
}

NegamaxAgent::NegamaxAgent(SearchConfig config,
                           TimeBudgetParams time_budget_params,
                           EvaluateStateFn evaluate_state_fn,
                           MovePriorityFn move_priority_fn,
                           ComputeTimeBudgetFn compute_time_budget_ms_fn)
    : config_(config),
      time_budget_params_(time_budget_params),
      evaluate_state_(std::move(evaluate_state_fn)),
      move_priority_(std::move(move_priority_fn)),
      compute_time_budget_ms_(std::move(compute_time_budget_ms_fn)),
      my_side_(0),
      state_(),
      tt_(config.tt_capacity)
{
}

void NegamaxAgent::set_side(bool plays_first)
{
    my_side_ = plays_first ? 0 : 1;
}

void NegamaxAgent::initialize(const std::vector<std::vector<int>>& board)
{
    state_.emplace(config_.rows, config_.cols, board);
    tt_.clear();
}

Move NegamaxAgent::choose_move(int my_time_ms, int /*opp_time_ms*/)
{
    ensure_initialized();

    const int legal_move_count = static_cast<int>(state_->legal_moves().size());
    const int time_budget_ms =
        compute_time_budget_ms_(my_time_ms, state_->undo_depth(),
                                legal_move_count, time_budget_params_);
    Move best_move =
        iterative_deepening(*state_, config_.max_depth, time_budget_ms).second;
    state_->apply(best_move);
    return best_move;
}

void NegamaxAgent::apply_opponent_move(Move move)
{
    ensure_initialized();
    if (state_->current_player() == 1 - my_side_) {
        state_->apply(move);
    }
}

void NegamaxAgent::ensure_initialized() const
{
    if (!state_.has_value()) {
        throw std::logic_error("AI state has not been initialized");
    }
}

void NegamaxAgent::order_moves(const State& state, std::vector<Move>& moves,
                               std::optional<Move> tt_best_move, int depth,
                               int ply, bool is_root) const
{
    std::sort(moves.begin(), moves.end(),
              [&](const Move& lhs, const Move& rhs) {
                  return move_priority_(state, lhs, tt_best_move, depth, ply,
                                        is_root) >
                         move_priority_(state, rhs, tt_best_move, depth, ply,
                                        is_root);
              });

    if (tt_best_move.has_value()) {
        auto tt_move = std::find(moves.begin(), moves.end(), *tt_best_move);
        if (tt_move != moves.end()) {
            std::iter_swap(moves.begin(), tt_move);
        }
    }
}

std::pair<int, Move> NegamaxAgent::negamax(
    State& state, int depth, int alpha, int beta, int player,
    std::chrono::steady_clock::time_point deadline, bool& timed_out, int ply,
    bool is_root)
{
    if (timed_out || std::chrono::steady_clock::now() >= deadline) {
        timed_out = true;
        return std::make_pair(0, PASS_MOVE);
    }

    if ((depth == 0) || state.is_terminal()) {
        return std::make_pair(evaluate_state_(state, player), PASS_MOVE);
    }

    const int original_alpha = alpha;
    const int original_beta = beta;
    const uint64_t key = state.hash();
    const TranspositionEntry* tt_entry = tt_.probe(key);
    if (tt_entry != nullptr && tt_entry->depth >= depth) {
        if (tt_entry->bound == BoundType::Exact) {
            return std::make_pair(tt_entry->value, tt_entry->best_move);
        }
        if (tt_entry->bound == BoundType::Lower) {
            alpha = std::max(alpha, tt_entry->value);
        } else if (tt_entry->bound == BoundType::Upper) {
            beta = std::min(beta, tt_entry->value);
        }
        if (alpha >= beta) {
            return std::make_pair(tt_entry->value, tt_entry->best_move);
        }
    }

    auto moves = state.legal_moves();
    order_moves(state, moves,
                tt_entry != nullptr ? std::optional<Move>(tt_entry->best_move)
                                    : std::nullopt,
                depth, ply, is_root);

    int value = -INF;
    Move best_move = PASS_MOVE;
    for (auto move : moves) {
        state.apply(move);
        int child_value = -negamax(state, depth - 1, -beta, -alpha,
                                   1 - player, deadline, timed_out, ply + 1,
                                   false)
                               .first;
        state.undo();
        if (timed_out) {
            return std::make_pair(0, PASS_MOVE);
        }
        if (child_value > value) {
            value = child_value;
            best_move = move;
        }
        alpha = std::max(alpha, value);
        if (alpha >= beta) {
            break;
        }
    }

    BoundType bound = BoundType::Exact;
    if (value <= original_alpha) {
        bound = BoundType::Upper;
    } else if (value >= original_beta) {
        bound = BoundType::Lower;
    }
    tt_.store(key, depth, value, best_move, bound);
    return std::make_pair(value, best_move);
}

std::pair<int, Move> NegamaxAgent::iterative_deepening(State& state,
                                                       int max_depth,
                                                       int time_budget_ms)
{
    const int safe_budget_ms = std::max(1, time_budget_ms);
    const auto deadline = std::chrono::steady_clock::now() +
                          std::chrono::milliseconds(safe_budget_ms);

    std::pair<int, Move> best_completed = std::make_pair(-INF, PASS_MOVE);
    for (int depth = 1; depth <= max_depth; ++depth) {
        bool timed_out = false;
        auto result = negamax(state, depth, -INF, INF, state.current_player(),
                              deadline, timed_out, 0, true);
        if (timed_out) {
            break;
        }
        best_completed = result;
    }
    return best_completed;
}
// end C:/Users/cttg8/Desktop/NYPC 2026/src/negamax_agent.cpp

// begin C:/Users/cttg8/Desktop/NYPC 2026/src/state.cpp

bool Move::is_pass() const
{
    return r1 == -1 && c1 == -1 && r2 == -1 && c2 == -1;
}

bool Move::operator==(const Move& other) const
{
    return r1 == other.r1 && c1 == other.c1 && r2 == other.r2 &&
           c2 == other.c2;
}

namespace {

uint64_t splitmix64(uint64_t x)
{
    x += 0x9e3779b97f4a7c15ull;
    x = (x ^ (x >> 30)) * 0xbf58476d1ce4e5b9ull;
    x = (x ^ (x >> 27)) * 0x94d049bb133111ebull;
    return x ^ (x >> 31);
}

}  // namespace

uint64_t State::zobrist_cell_value(int pos, uint8_t value)
{
    return splitmix64(0x243f6a8885a308d3ull ^
                      (static_cast<uint64_t>(pos) << 8) ^ value);
}

uint64_t State::zobrist_cell_owner(int pos, int8_t owner)
{
    return splitmix64(0x13198a2e03707344ull ^
                      (static_cast<uint64_t>(pos) << 2) ^
                      static_cast<uint64_t>(owner + 1));
}

uint64_t State::zobrist_player(int player)
{
    return splitmix64(0xa4093822299f31d0ull ^ static_cast<uint64_t>(player));
}

uint64_t State::zobrist_passes(int passes)
{
    return splitmix64(0x082efa98ec4e6c89ull ^
                      static_cast<uint64_t>(std::min(passes, 2)));
}

uint64_t State::zobrist_dimensions(int rows, int cols)
{
    return splitmix64(0x452821e638d01377ull ^
                      (static_cast<uint64_t>(rows) << 32) ^
                      static_cast<uint64_t>(cols));
}

State::State(int rows, int cols, const std::vector<std::vector<int>>& init_grid)
    : rows_(rows),
      cols_(cols),
      grid_(),
      owners_(),
      current_player_(0),
      consecutive_passes_(0),
      zobrist_key_(0),
      undo_stack_()
{
    if (rows_ <= 0 || cols_ <= 0) {
        throw std::invalid_argument("State dimensions must be positive");
    }
    if (static_cast<int>(init_grid.size()) != rows_) {
        throw std::invalid_argument("Initial grid row count does not match rows");
    }

    grid_.reserve(static_cast<size_t>(rows_) * static_cast<size_t>(cols_));
    for (int r = 0; r < rows_; ++r) {
        if (static_cast<int>(init_grid[r].size()) != cols_) {
            throw std::invalid_argument("Initial grid column count does not match cols");
        }
        for (int c = 0; c < cols_; ++c) {
            if (init_grid[r][c] < -128 || init_grid[r][c] > 127) {
                throw std::invalid_argument("Cell value does not fit in int8_t");
            }
            grid_.push_back(static_cast<int8_t>(init_grid[r][c]));
        }
    }
    owners_.assign(grid_.size(), static_cast<int8_t>(-1));
    zobrist_key_ = compute_zobrist_key();
}

State State::clone() const
{
    State copy(*this);
    copy.undo_stack_.clear();
    return copy;
}

void State::apply(Move m)
{
    if (!is_legal(m)) {
        throw std::invalid_argument("Illegal move");
    }

    UndoRecord record;
    record.move = m;
    record.prev_consecutive_passes = consecutive_passes_;
    record.prev_player = current_player_;
    record.prev_hash = zobrist_key_;

    if (m.is_pass()) {
        zobrist_key_ ^= zobrist_player(current_player_);
        zobrist_key_ ^= zobrist_passes(consecutive_passes_);
        ++consecutive_passes_;
        current_player_ = 1 - current_player_;
        zobrist_key_ ^= zobrist_player(current_player_);
        zobrist_key_ ^= zobrist_passes(consecutive_passes_);
        undo_stack_.push_back(std::move(record));
        return;
    }

    for (int r = m.r1; r <= m.r2; ++r) {
        for (int c = m.c1; c <= m.c2; ++c) {
            const int pos = idx(r, c);
            const int8_t new_val = 0;
            const int8_t new_owner = static_cast<int8_t>(current_player_);
            if (grid_[pos] != new_val || owners_[pos] != new_owner) {
                record.deltas.push_back({pos, grid_[pos], owners_[pos]});
            }
        }
    }

    for (const UndoRecord::CellDelta& delta : record.deltas) {
        zobrist_key_ ^= zobrist_cell_value(delta.idx, static_cast<uint8_t>(delta.old_val));
        zobrist_key_ ^= zobrist_cell_owner(delta.idx, delta.old_owner);
        grid_[delta.idx] = 0;
        owners_[delta.idx] = static_cast<int8_t>(current_player_);
        zobrist_key_ ^= zobrist_cell_value(delta.idx, 0);
        zobrist_key_ ^= zobrist_cell_owner(delta.idx, static_cast<int8_t>(current_player_));
    }

    zobrist_key_ ^= zobrist_player(current_player_);
    zobrist_key_ ^= zobrist_passes(consecutive_passes_);
    consecutive_passes_ = 0;
    current_player_ = 1 - current_player_;
    zobrist_key_ ^= zobrist_player(current_player_);
    zobrist_key_ ^= zobrist_passes(consecutive_passes_);
    undo_stack_.push_back(std::move(record));
}

void State::undo()
{
    if (undo_stack_.empty()) {
        throw std::out_of_range("No move to undo");
    }

    UndoRecord record = std::move(undo_stack_.back());
    undo_stack_.pop_back();

    for (const UndoRecord::CellDelta& delta : record.deltas) {
        grid_[delta.idx] = delta.old_val;
        owners_[delta.idx] = delta.old_owner;
    }
    consecutive_passes_ = record.prev_consecutive_passes;
    current_player_ = record.prev_player;
    zobrist_key_ = record.prev_hash;
}

int State::undo_depth() const
{
    return static_cast<int>(undo_stack_.size());
}

std::vector<Move> State::legal_moves() const
{
    std::vector<Move> moves;
    std::vector<int> col_sum(cols_, 0);

    for (int r1 = 0; r1 < rows_; ++r1) {
        std::fill(col_sum.begin(), col_sum.end(), 0);

        for (int r2 = r1; r2 < rows_; ++r2) {
            for (int c = 0; c < cols_; ++c) {
                col_sum[c] += grid_[idx(r2, c)];
            }

            int c1 = 0;
            int sum = 0;
            for (int c2 = 0; c2 < cols_; ++c2) {
                sum += col_sum[c2];

                while (c1 <= c2 && sum > 10) {
                    sum -= col_sum[c1];
                    ++c1;
                }

                if (sum == 10) {
                    for (int left = c1; left <= c2; ++left) {
                        if (border_ok(r1, left, r2, c2)) {
                            moves.push_back({r1, left, r2, c2});
                        }
                        if (col_sum[left] != 0) {
                            break;
                        }
                    }
                }
            }
        }
    }

    moves.push_back(PASS_MOVE);
    return moves;
}

bool State::is_legal(const Move& m) const
{
    if (m.is_pass()) {
        return true;
    }

    if (m.r1 < 0 || m.c1 < 0 || m.r2 < 0 || m.c2 < 0 || m.r1 > m.r2 ||
        m.c1 > m.c2 || m.r2 >= rows_ || m.c2 >= cols_) {
        return false;
    }

    int sum = 0;
    for (int r = m.r1; r <= m.r2; ++r) {
        for (int c = m.c1; c <= m.c2; ++c) {
            sum += grid_[idx(r, c)];
        }
    }

    return sum == 10 && border_ok(m.r1, m.c1, m.r2, m.c2);
}

bool State::is_terminal() const
{
    return consecutive_passes_ >= 2;
}

std::pair<int, int> State::scores() const
{
    int p0 = 0;
    int p1 = 0;
    for (int8_t owner : owners_) {
        if (owner == 0) {
            ++p0;
        } else if (owner == 1) {
            ++p1;
        }
    }
    return {p0, p1};
}

int State::winner() const
{
    const std::pair<int, int> score = scores();
    if (score.first > score.second) {
        return 0;
    }
    if (score.second > score.first) {
        return 1;
    }
    return -1;
}

double State::reward(int player) const
{
    if (player != 0 && player != 1) {
        throw std::invalid_argument("Player must be 0 or 1");
    }
    const int result = winner();
    if (result == -1) {
        return 0.5;
    }
    return result == player ? 1.0 : 0.0;
}

int State::current_player() const
{
    return current_player_;
}

int State::rows() const
{
    return rows_;
}

int State::cols() const
{
    return cols_;
}

int8_t State::cell_value(int r, int c) const
{
    if (r < 0 || c < 0 || r >= rows_ || c >= cols_) {
        throw std::out_of_range("Cell coordinates are out of bounds");
    }
    return grid_[idx(r, c)];
}

int8_t State::cell_owner(int r, int c) const
{
    if (r < 0 || c < 0 || r >= rows_ || c >= cols_) {
        throw std::out_of_range("Cell coordinates are out of bounds");
    }
    return owners_[idx(r, c)];
}

bool State::operator==(const State& other) const
{
    return rows_ == other.rows_ && cols_ == other.cols_ &&
           grid_ == other.grid_ && owners_ == other.owners_ &&
           current_player_ == other.current_player_ &&
           consecutive_passes_ == other.consecutive_passes_;
}

uint64_t State::hash() const
{
    return zobrist_key_;
}

std::string State::to_string() const
{
    std::ostringstream out;
    out << "player=" << current_player_ << " passes=" << consecutive_passes_
        << '\n';
    for (int r = 0; r < rows_; ++r) {
        for (int c = 0; c < cols_; ++c) {
            const int pos = idx(r, c);
            if (grid_[pos] > 0) {
                out << static_cast<int>(grid_[pos]);
            } else if (owners_[pos] == -1) {
                out << '.';
            } else {
                out << static_cast<char>('A' + owners_[pos]);
            }
            if (c + 1 < cols_) {
                out << ' ';
            }
        }
        if (r + 1 < rows_) {
            out << '\n';
        }
    }
    return out.str();
}

bool State::border_ok(int r1, int c1, int r2, int c2) const
{
    bool top = false;
    bool bottom = false;
    bool left = false;
    bool right = false;

    for (int c = c1; c <= c2; ++c) {
        top = top || grid_[idx(r1, c)] >= 1;
        bottom = bottom || grid_[idx(r2, c)] >= 1;
    }
    for (int r = r1; r <= r2; ++r) {
        left = left || grid_[idx(r, c1)] >= 1;
        right = right || grid_[idx(r, c2)] >= 1;
    }

    return top && bottom && left && right;
}

int State::idx(int r, int c) const
{
    return r * cols_ + c;
}

uint64_t State::compute_zobrist_key() const
{
    uint64_t key = zobrist_dimensions(rows_, cols_);
    for (int pos = 0; pos < static_cast<int>(grid_.size()); ++pos) {
        key ^= zobrist_cell_value(pos, static_cast<uint8_t>(grid_[pos]));
        key ^= zobrist_cell_owner(pos, owners_[pos]);
    }
    key ^= zobrist_player(current_player_);
    key ^= zobrist_passes(consecutive_passes_);
    return key;
}
// end C:/Users/cttg8/Desktop/NYPC 2026/src/state.cpp

// begin C:/Users/cttg8/Desktop/NYPC 2026/src/tt.cpp


TranspositionTable::TranspositionTable(size_t capacity)
    : entries_(capacity), used_(0)
{
    if (capacity == 0) {
        throw std::invalid_argument("TT capacity must be positive");
    }
}

const TranspositionEntry* TranspositionTable::probe(uint64_t key) const
{
    const TranspositionEntry& entry = entries_[index(key)];
    if (entry.occupied && entry.key == key) {
        return &entry;
    }
    return nullptr;
}

void TranspositionTable::store(uint64_t key, int depth, int value,
                               Move best_move, BoundType bound)
{
    TranspositionEntry& entry = entries_[index(key)];
    if (!entry.occupied) {
        ++used_;
    }
    entry = {key, depth, value, best_move, bound, true};
}

size_t TranspositionTable::size() const
{
    return used_;
}

size_t TranspositionTable::capacity() const
{
    return entries_.size();
}

void TranspositionTable::clear()
{
    std::fill(entries_.begin(), entries_.end(), TranspositionEntry{});
    used_ = 0;
}

size_t TranspositionTable::index(uint64_t key) const
{
    return static_cast<size_t>(key % entries_.size());
}
// end C:/Users/cttg8/Desktop/NYPC 2026/src/tt.cpp

// begin C:/Users/cttg8/Desktop/NYPC 2026/src/main.cpp



int main()
{
    std::unique_ptr<Agent> ai = std::make_unique<NegamaxAgent>();

    char line[1024];
    char command[32];
    while (fgets(line, sizeof(line), stdin))
    {
        if (sscanf(line, "%s", command) != 1)
            continue;

        if (strcmp(command, "READY") == 0)
        {
            // Check if this player goes first
            char turn[32];
            sscanf(line, "%*s %s", turn);
            ai->set_side(strcmp(turn, "FIRST") == 0);
            printf("OK\n");
            fflush(stdout);
            continue;
        }

        if (strcmp(command, "INIT") == 0)
        {
            char *token = strtok(line, " ");
            std::vector<std::vector<int>> board;
            for (int i = 0; i < R; i++)
            {
                std::vector<int> temp;
                token = strtok(NULL, " ");
                for (int j = 0; j < C; j++) temp.push_back(token[j] - '0');
                board.push_back(temp);
            }
            ai->initialize(board);
            continue;
        }

        if (strcmp(command, "TIME") == 0)
        {
            // My turn: calculate and execute move
            int my_time, opp_time;
            sscanf(line, "%*s %d %d", &my_time, &opp_time);
            Move best_move = ai->choose_move(my_time, opp_time);

            auto [r1, c1, r2, c2] = best_move;
            printf("%d %d %d %d\n", r1, c1, r2, c2);
            fflush(stdout);
            continue;
        }

        if (strcmp(command, "OPP") == 0)
        {
            // Apply opponent's turn
            int r1, c1, r2, c2, time;
            sscanf(line, "%*s %d %d %d %d %d", &r1, &c1, &r2, &c2, &time);
            Move move = {r1, c1, r2, c2};
            ai->apply_opponent_move(move);
            continue;
        }

        if (strcmp(command, "FINISH") == 0)
            break;

        // Handle invalid command
        fprintf(stderr, "Invalid command: %s\n", command);
        return 1;
    }

    return 0;
}
// end C:/Users/cttg8/Desktop/NYPC 2026/src/main.cpp
